### ISSUE TITLE
It would be nice to have a Toggle for all the Default changes

### ISSUE THREAD

**Issue by MicManGuy** [fig02/Better-OoT#16]
A lot of these features are always applied without the option to toggle them off. Most people who use the app now will always want them. But giving the option to disable them can open up some interesting uses for BOoT.

For example, OoT Online will only support version 1.0. So in other words, Master Quest is not supported in OoT Online. However, using BOoT, you can patch 1.0 to have the MQ dungeons. Circumventing this problem entirely! But a lot of casual players might want to play mostly vanilla. The same is true for the other features. Maybe someone wants to keep all cutscenes, but still have just the option to skip owls, or just have D-Pad Boots, or a just few cosmetic changes, etc.

A single toggle for all of the default features would open up the app to many more people.

Of course, ideally, every tiny little feature would have a toggle. But that gets a bit tedious. It's a quick fix to do them all with a single toggle. Although, If you did want to do that, you could make some sort of "Advanced" tab for disabling default features one at a time. People love customizing their experience.

**Comment by fig02** [comment]
Hi
Thank you for your suggestion.
This tool was designed specifically for speedrunning, and the settings options are perfect for what it was designed for. I definitely see how it could be opened up to serve more purposes, but I will not be the one to implement that since this fits me and my community's needs already.

Sorry and thank you for understanding
